[[bin]]
name = "lmsg-server"
path = "src/server/main.rs"
[package]
name = "lmsg-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }

[[bin]]
name = "lmsg-client"
path = "src/client/main.rs"
version = "0.1.0"
edition = "2021"
